<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <RootNamespace>Singulink.Cryptography</RootNamespace>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Singulink/Singulink.Cryptography.PasswordHasher</PackageProjectUrl>
    <Authors>Singulink</Authors>
    <Description>Adds Argon2 hash algorithm support for Singulink.Cryptography.PasswordHasher.</Description>
    <Copyright>© Singulink. All rights reserved.</Copyright>
    <PackageIcon>Singulink Icon 128x128.png</PackageIcon>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
    <Version>3.0</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup Label="Source Link" Condition="'$(Configuration)' == 'Release'">
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Resources\Singulink Icon 128x128.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Singulink.Cryptography.PasswordHasher\Singulink.Cryptography.PasswordHasher.csproj" />
  </ItemGroup>
</Project>
